<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UJ2963A" failures="1" tests="8" name="com.test.ProductPageTest" time="230.605" errors="0" timestamp="2023-05-29T10:53:30 GMT-07:00" skipped="4">
  <testcase classname="com.test.ProductPageTest" name="validateTheElementInAddProductPopup" time="48.935"/>
  <system-out/>
  <testcase classname="com.test.ProductPageTest" name="validateValueEntredInAddProductPopUpFieldIsSaved" time="32.383">
    <skipped/>
  </testcase> <!-- validateValueEntredInAddProductPopUpFieldIsSaved -->
  <system-out/>
  <testcase classname="com.test.ProductPageTest" name="validateValueEntredInAddProductPopUpFieldIsSaved" time="31.352">
    <skipped/>
  </testcase> <!-- validateValueEntredInAddProductPopUpFieldIsSaved -->
  <system-out/>
  <testcase classname="com.test.ProductPageTest" name="validateValueEntredInAddProductPopUpFieldIsSaved" time="31.129">
    <skipped/>
  </testcase> <!-- validateValueEntredInAddProductPopUpFieldIsSaved -->
  <system-out/>
  <testcase classname="com.test.ProductPageTest" name="validateValueEntredInAddProductPopUpFieldIsSaved" time="31.887">
    <failure message="The following asserts failed:
	failure message: product code not found expected [101] but found [0],
	failure message: product Name not found expected [Maza] but found [APPLE],
	failure message: product description not found expected [Hello] but found [FRESH],
	failure message: product tax not found expected [10] but found [18],
	failure message: product price not found expected [10] but found [10.000 x8fmv]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
failure message: product code not found expected [101] but found [0],
failure message: product Name not found expected [Maza] but found [APPLE],
failure message: product description not found expected [Hello] but found [FRESH],
failure message: product tax not found expected [10] but found [18],
failure message: product price not found expected [10] but found [10.000 x8fmv]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.test.ProductPageTest.validateValueEntredInAddProductPopUpFieldIsSaved(ProductPageTest.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateValueEntredInAddProductPopUpFieldIsSaved -->
  <system-out/>
  <testcase classname="com.test.ProductPageTest" name="validateValueEntredInAddProductPopUpFieldIsSaved" time="31.959">
    <skipped/>
  </testcase> <!-- validateValueEntredInAddProductPopUpFieldIsSaved -->
  <system-out/>
  <testcase classname="com.test.ProductPageTest" name="validateEditFunctionOfExistingRecord" time="11.137"/>
  <system-out/>
  <testcase classname="com.test.ProductPageTest" name="validateDeleteFunctiongOfExistingRecord" time="11.823"/>
  <system-out/>
</testsuite> <!-- com.test.ProductPageTest -->
