<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="7" passed="2" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-23T21:22:38 IST" name="Suite" finished-at="2023-05-23T21:32:39 IST" duration-ms="600479">
    <groups>
      <group name="smoke">
        <method signature="LoginPageTest.validateLogin()[pri:0, instance:com.test.LoginPageTest@55182842]" name="validateLogin" class="com.test.LoginPageTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-05-23T21:22:38 IST" name="ChromeTest" finished-at="2023-05-23T21:32:39 IST" duration-ms="600479">
      <class name="com.test.ProductPageTest">
        <test-method is-config="true" signature="prerun()[pri:0, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:23:03 IST" name="prerun" finished-at="2023-05-23T21:24:47 IST" duration-ms="103738" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prerun -->
        <test-method signature="validateTheElementInAddProductPopup()[pri:1, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:24:47 IST" name="validateTheElementInAddProductPopup" finished-at="2023-05-23T21:25:50 IST" duration-ms="63235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTheElementInAddProductPopup -->
        <test-method is-config="true" signature="prerun()[pri:0, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:25:50 IST" name="prerun" finished-at="2023-05-23T21:27:31 IST" duration-ms="101466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prerun -->
        <test-method signature="validatenAddStoresPopUpfields()[pri:2, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:27:31 IST" name="validatenAddStoresPopUpfields" finished-at="2023-05-23T21:27:31 IST" duration-ms="6" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Error during reading file]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Error during reading file
at com.utils.ExcelUtils.readStringData(ExcelUtils.java:61)
at com.test.ProductPageTest.validatenAddStoresPopUpfields(ProductPageTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatenAddStoresPopUpfields -->
        <test-method is-config="true" signature="prerun()[pri:0, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:27:32 IST" name="prerun" finished-at="2023-05-23T21:29:13 IST" duration-ms="101581" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prerun -->
        <test-method signature="validateValueEntredInAddProductPopUpIsSaved()[pri:3, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:29:13 IST" name="validateValueEntredInAddProductPopUpIsSaved" finished-at="2023-05-23T21:29:15 IST" duration-ms="1122" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Error during reading file]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Error during reading file
at com.utils.ExcelUtils.readStringData(ExcelUtils.java:61)
at com.test.ProductPageTest.validateValueEntredInAddProductPopUpIsSaved(ProductPageTest.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateValueEntredInAddProductPopUpIsSaved -->
        <test-method is-config="true" signature="prerun()[pri:0, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:29:15 IST" name="prerun" finished-at="2023-05-23T21:30:56 IST" duration-ms="101417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prerun -->
        <test-method signature="validateEditFunctionOfExistingRecord()[pri:4, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:30:56 IST" name="validateEditFunctionOfExistingRecord" finished-at="2023-05-23T21:30:56 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Error during reading file]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Error during reading file
at com.utils.ExcelUtils.readStringData(ExcelUtils.java:61)
at com.test.ProductPageTest.validateEditFunctionOfExistingRecord(ProductPageTest.java:144)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEditFunctionOfExistingRecord -->
        <test-method is-config="true" signature="prerun()[pri:0, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:30:57 IST" name="prerun" finished-at="2023-05-23T21:32:38 IST" duration-ms="101560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prerun -->
        <test-method signature="validateDeleteFunctiongOfExistingRecord()[pri:5, instance:com.test.ProductPageTest@71d44a3]" started-at="2023-05-23T21:32:38 IST" name="validateDeleteFunctiongOfExistingRecord" finished-at="2023-05-23T21:32:38 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Error during reading file]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Error during reading file
at com.utils.ExcelUtils.readStringData(ExcelUtils.java:61)
at com.test.ProductPageTest.validateDeleteFunctiongOfExistingRecord(ProductPageTest.java:177)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteFunctiongOfExistingRecord -->
      </class> <!-- com.test.ProductPageTest -->
      <class name="com.test.LoginPageTest">
        <test-method is-config="true" signature="preLaunch(java.lang.String)[pri:0, instance:com.test.LoginPageTest@55182842]" started-at="2023-05-23T21:22:39 IST" name="preLaunch" finished-at="2023-05-23T21:23:00 IST" duration-ms="21053" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preLaunch -->
        <test-method signature="validateLogin()[pri:0, instance:com.test.LoginPageTest@55182842]" started-at="2023-05-23T21:23:00 IST" name="validateLogin" finished-at="2023-05-23T21:23:03 IST" duration-ms="2534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin -->
      </class> <!-- com.test.LoginPageTest -->
    </test> <!-- ChromeTest -->
  </suite> <!-- Suite -->
</testng-results>
